### ISSUE TITLE
支持NSInvocation吗？

### ISSUE THREAD

**Issue by unkosun** [kudocc/WTTimer#1]
你好，目前好像还没有支持NSInvocation吗？

**Comment by kudocc** [comment]
不支持NSInvocation，本来是尝试着支持的，但是后来发现在invoke的时候会retain住target

**Comment by unkosun** [comment]
我尝试了下，在调用invocation的时候 重新创建一个新的invocation 然后invoke 调用完后释放调就可以了

**Comment by kudocc** [comment]
嗯，这是个不错的办法！

**Comment by kudocc** [comment]
@unkosun Fixed it! Thanks very much.
